site:
  name: 'Pilot Reporting Task Force'
  site: 'https://pilotreportingtf.github.io'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: 'Home'
    template: '%s — Pilot Reporting Task Force'
  description: "\U0001F680 "
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Pilot Reporting Task Force'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  #theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
  theme: 'dark'
